# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5190/base-registry-db"
    username: "postgres"
    password: "secret"
  jpa:
    properties:
      hibernate:
        ddl-auto: create
