# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

server:
  port: 8190

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true

spring:
  application:
    name: base-registry-data-service
  datasource:
    hikari:
      schema: ${spring.jpa.properties.hibernate.default_schema}
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: data
        ddl-auto: validate

springdoc:
  api-docs:
    path: /api-docs
    enabled: "${INTEGRATED_WEB_DOCS_ENABLE:true}"
  swagger-ui:
    path: /swagger-ui.html
    enabled: "${INTEGRATED_WEB_DOCS_ENABLE:true}"
  show-actuator: "${INTEGRATED_WEB_DOCS_ENABLE:true}"

logging:
  level:
    org:
      springframework:
        security: DEBUG
